### ISSUE TITLE
Error when logging into spud admin without the Super Admin role

### ISSUE THREAD

**Issue by randeffects** [spud-grails/spud-security#2]
When I try to create an account that does not have the `Super Admin` role I get an error on login.  If the same user has the `Super Admin` role, there is no error.  Grails produces an exception `No such property: spudSecureAnnotation for class: spud.security.SpudSecurityBridge.`

NGINX and Grails exceptions are below:

```
[15/Jun/2015:14:42:25 +0000] "GET /spud/admin HTTP/1.1" 302 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Firefox/38.0"
[15/Jun/2015:14:42:25 +0000] "GET /login/auth HTTP/1.1" 200 621 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Firefox/38.0"
[15/Jun/2015:14:42:29 +0000] "POST /j_spring_security_check HTTP/1.1" 302 0 "login/auth" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Firefox/38.0"
[15/Jun/2015:14:42:29 +0000] "GET /login/authfail?login_error=1 HTTP/1.1" 302 0 "/login/auth" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Firefox/38.0"
[15/Jun/2015:14:42:29 +0000] "GET /login/auth?login_error=1 HTTP/1.1" 200 684 "/login/auth" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Firefox/38.0"
[15/Jun/2015:14:42:50 +0000] "POST /j_spring_security_check HTTP/1.1" 302 0 "/login/auth?login_error=1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Firefox/38.0"
[15/Jun/2015:14:42:50 +0000] "GET /spud/admin HTTP/1.1" 500 1593 "/login/auth?login_error=1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Firefox/38.0"

errors.GrailsExceptionResolver MissingPropertyException occurred when processing request: [GET] /spud/admin
No such property: spudSecureAnnotation for class: spud.security.SpudSecurityBridge. Stacktrace follows:
groovy.lang.MissingPropertyException: No such property: spudSecureAnnotation for class: spud.security.SpudSecurityBridge
        at spud.security.SpudSecurityBridge.hasRole(SpudSecurityBridge.groovy:86)
        at org.grails.plugin.securitybridge.SharedSecurityService$_hasAnyRole_closure1.doCall(SharedSecurityService.groovy:108)
        at org.grails.plugin.securitybridge.SharedSecurityService.hasAnyRole(SharedSecurityService.groovy:107)
        at spud.core.SecurityFilters$_closure1_closure2_closure3.doCall(SecurityFilters.groovy:34)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:177)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at com.oohlalog.grails.OohLaLogAuthenticationFilter.doFilter(OohLaLogAuthenticationFilter.groovy:45)
        at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)
        at grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter.doFilter(RequestHolderAuthenticationFilter.java:49)
        at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:82)
        at spud.permalinks.PermalinkFilter.doFilter(PermalinkFilter.groovy:67)
        at spud.core.SpudMultiSiteFilter.doFilter(SpudMultiSiteFilter.groovy:27)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by tjrafferty** [comment]
Experiencing the same issue and noticed that spudSecureAnnotation() is missing.
see here: http://bertram.d.pr/14uck
